apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name}}-{{ .Chart.Name}}
    app.kubernetes.io/part-of: {{ .Chart.Name}}
    app.kubernetes.io/version: {{ .Chart.AppVersion}}
  name: {{ .Release.Name}}-{{ .Chart.Name}}
  namespace: {{ .Release.Namespace}}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name}}-{{ .Chart.Name}}
      app.kubernetes.io/part-of: {{ .Chart.Name}}
      app.kubernetes.io/version: {{ .Chart.AppVersion}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name}}-{{ .Chart.Name}}
        app.kubernetes.io/part-of: {{ .Chart.Name}}
        app.kubernetes.io/version: {{ .Chart.AppVersion}}
    spec:
      containers:
      - name: {{ .Release.Name}}-{{ .Chart.Name}}
        image: {{ .Values.imageRepo}}:{{ .Values.imageTag}}
        ports:
        - containerPort: {{ .Values.containerPort}}
