apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name}}-{{ .Chart.Name}}
    app.kubernetes.io/part-of: {{ .Chart.Name}}
    app.kubernetes.io/version: {{ .Chart.AppVersion}}
  name: {{ .Release.Name}}-{{ .Chart.Name}}-ingress
  namespace: {{ .Release.Namespace}}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingressHost}}
      secretName: {{ .Values.tlsSecret}}
  rules:
  - host: {{ .Values.ingressHost}}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: blog
            port: 
              number: {{ .Values.servicePort}}