apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-{{ .Chart.Name}}-svc
  namespace: {{ .Release.Namespace}}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ .Release.Name}}-{{ .Chart.Name}}
  ports:
  - port: {{ .Values.servicePort}}
    targetPort: {{ .Values.containerPort}}
