apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog
  labels:
    name: blog
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - nadidurna.com
      secretName: cert-secret
  rules:
  - host: nadidurna.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: blog
            port: 
              number: 80
